### ISSUE TITLE
API v1 will be turned off. 

### ISSUE THREAD

**Issue by stccorp** [f4bsch/DropPHP#15]
I received an email from Dropbox that API v1 will be turned off on june 28 2017

Will this has any effect on DropPHP library?

Thank you

**Comment by f4bsch** [comment]
Yes, the current version will stop working. I'm working on a port to v2 though.

**Comment by standus** [comment]
Any progress?

**Comment by f4bsch** [comment]
I'm working on it, should be done by the weekend.

**Comment by standus** [comment]
Any progress?

**Comment by standus** [comment]
Which weekend you meant?

**Comment by f4bsch** [comment]
Sorry for the delay. Its more work than I expected.

I just pushed a first v2 version, only authentication, file listing, thumbnails, search, download and upload is working.

https://github.com/f4bsch/DropPHP/tree/api-v2

**Comment by f4bsch** [comment]
Note that the authentication process has changed (OAuth2). See sample.php .

**Comment by nmaas87** [comment]
Thank you very much!

**Comment by nmaas87** [comment]
Thank you very much, it works! 👍

**Comment by standus** [comment]
My first test failed.
![screenshot 2016-09-24 22 11 29](https://cloud.githubusercontent.com/assets/4818430/18810967/1b3394ae-82a4-11e6-809e-77a266dfa86b.jpg)
![screenshot 2016-09-24 22 04 32](https://cloud.githubusercontent.com/assets/4818430/18810968/1b3d8c7a-82a4-11e6-8beb-32e819ed3325.jpg)

**Comment by standus** [comment]
Then another fault:
![screenshot 2016-09-24 22 34 52](https://cloud.githubusercontent.com/assets/4818430/18811139/cb3ce208-82a7-11e6-866f-5672034b63ac.jpg)

GetFiles() function return objects in array, but expexted arrays at all paths. In previous version of your class is was correct.

**Comment by standus** [comment]
On PHP 5.6 error:
Only variables should be passed by reference
for example this line:
return $this->apiCall("2/files/upload", $commit_params, true, file_get_contents($src_file));

**Comment by simube** [comment]
When do you plan to release a final version?
The file things work for me, but I need account quota too, to update the script.

**Comment by alsanan** [comment]
Somebody here? DropPHP will stop working on june...

**Comment by nmaas87** [comment]
As @f4bsch wrote, (https://github.com/f4bsch/DropPHP/issues/15#issuecomment-247988373) a part of the featureset of DropPHP is already working - and I also got it running. I would advise to switch to this version if it fits your needs :).

**Comment by simube** [comment]
changing the functions is not a big deal, but I'm not used to work with git, so I'm not able to publish my changes (for me, the script now works with the functions I use...)

**Comment by petenice** [comment]
Hello thread, thank you for the efforts here, Dropbox API V1 endpoints will stop working on September 28th 2017, I'm very much hoping the DropPHP V2 update will be completed soon. Thank you!

**Comment by gety9** [comment]
Is it updated now to api v2?

**Comment by bilke** [comment]
@gety9 I can confirm that the current master-branch works with API v2. Although I had to make a small fix, see #23.

**Comment by f4bsch** [comment]
I confirm, current master branch is v2 compatible. 

@bilke thanks for the PR, I'll review

**Comment by adilbo** [comment]
could you please also update the sample.php - it's not switched to v2 yet ;-) thanx

**Comment by f4bsch** [comment]
@adilbo I updated the samples
