### ISSUE TITLE
Update Script for API v2?

### ISSUE THREAD

**Issue by simube** [f4bsch/DropPHP#18]
Hi

Thanks for your great script!
When do you plan updating the functions for API v2? I need some functions, which do not yet work in your v2 script.
Otherwise I have to look for another class :(

**Comment by alsanan** [comment]
+1
Deprecation date is on june 2017. After then, every script using DropPHP will stop working. Not nice.

**Comment by micha137** [comment]
This is a duplicate of #15.

**Comment by f4bsch** [comment]
DropPHP now supports v2
