### ISSUE TITLE
chunked upload not working in current

### ISSUE THREAD

**Issue by stanislavlukacik** [f4bsch/DropPHP#26]
some points to get it working

/upload_session/start must be called with content type set, can upload first chunk 

/upload_session/append_v2 return nothing, check for returned json call the exception

/upload_session/finish must be called with offset = whole_file_size, content type header filled must be too

altered source attached
[DropboxClient.php.txt](https://github.com/f4bsch/DropPHP/files/1345112/DropboxClient.php.txt)

**Comment by f4bsch** [comment]
Thanks! Im working on it

**Comment by f4bsch** [comment]
Fixed
