### ISSUE TITLE
$dropbox->CreateFolder doesn't work without this edit to DropboxClient.php

### ISSUE THREAD

**Issue by Maffyou** [f4bsch/DropPHP#27]
Hi,

First of all, thanks for making DropPHP!

I'm using the v2 branch, and have it (almost) working.

When trying:
`$dropbox->CreateFolder('newFolder');`
I get this error:

> Fatal error: Uncaught exception 'DropboxException' with message 'apiCall(2/files/create_folder_v2) failed: Error in call to API function "files/create_folder_v2": request body: unknown field 'root' (URL was https://api.dropboxapi.com/2/files/create_folder_v2)' in /home/ubuntu/workspace/dropphp/DropboxClient.php on line 624 DropboxException: apiCall(2/files/create_folder_v2) failed: Error in call to API function "files/create_folder_v2": request body: unknown field 'root' (URL was https://api.dropboxapi.com/2/files/create_folder_v2) in /home/ubuntu/workspace/dropphp/DropboxClient.php on line 624 Call Stack: 0.0007 239280 1. {main}() /home/ubuntu/workspace/dropphp/dropbox-createCasefileFolder.php:0 0.0032 269416 2. DropboxClient->CreateFolder() /home/ubuntu/workspace/dropphp/dropbox-createCasefileFolder.php:23 0.0032 270056 3. DropboxClient->apiCall() /home/ubuntu/workspace/dropphp/DropboxClient.php:484 0.0032 270328 4. DropboxClient->doSingleCall() /home/ubuntu/workspace/dropphp/DropboxClient.php:658

In DropboxClient.php line 484 I changed this:
`array('root' => $this->rootPath, 'path' => $path));`
to this:
`array('path' => $path));`
...and it now works.

Was this a fluke, or is it the actual solution?

Thanks in advance.

**Comment by f4bsch** [comment]
The function was still using the old v1 protocol. I just pushed a fix
