### ISSUE TITLE
Issue with MAX_UPLOAD_CHUNK_SIZE = 150 * 1024 * 1024;

### ISSUE THREAD

**Issue by Maffyou** [f4bsch/DropPHP#30]
Hi,

Just downloaded the latest version (EDIT: 2.0.0). It threw PHP errors regarding lines 20, 21, 847 and 848.

These lines all include a calculation in the format "150 * 1024 * 1024".

I replaced those calculations with integers equal to the result of the calc and it now works.

**Comment by mdreier** [comment]
This is caused by an old PHP version. Support for constant expressions was added in PHP 5.6.0 (see [Documentation](http://php.net/manual/en/language.oop5.constants.php)).

Updating my installation to PHP 5.6.33 resolved the issue for me.

**Comment by Maffyou** [comment]
Nice. Thank you.

**Comment by mdreier** [comment]
@f4bsch: Maybe you could add a note to the README with the required PHP version.
